# WARNING - Generated by {fusen} from /dev/flat_ggplot_theme.Rmd: do not edit by hand

test_that("check_font_families works", {

  data(toy_raw_file_content)

  result_ggplot_theme <- toy_raw_file_content %>% extract_ggplot_theme()
  
  expect_message(object = result_ggplot_theme %>% check_font_families(),
                 regexp = NA)
  
  })
