# Generated by fusen: do not edit by hand

test_that("get_file_content() works", {

  file_content <- get_file_content(file_key = "wRqIvMmymzSPuj0sEhnORb",
                                 acess_token = Sys.getenv("FIGMA_TOKEN"))
  
  expect_equal(object = get_ggplot_element_design(name_ggplot_element = "panel_background", 
                                                  file_content = file_content), 
               expected = list(fill_color = "#5FBDDE", 
                               fill_opacity = 0.600000023841858, 
                               stroke_color = "#D29F9F", 
                               stroke_opacity = 1, 
                               stroke_weight = 4)
  )
 
})
