# WARNING - Generated by {fusen} from /dev/flat_figma_design_extraction.Rmd: do not edit by hand

test_that("add_ggplot_type() works", {
  
  data(toy_raw_file_content)
  
  data_with_type <- toy_raw_file_content %>% 
    raw_to_design_tibble() %>% 
    add_ggplot_type()

  # long dput ----
  expect_equal(object = data_with_type, 
               expected = structure(list(element_name = c("panel_background", "legend_text", 
                                                          "legend_title", "panel_grid", "axis_text", "axis_title", "plot_subtitle", 
                                                          "plot_title"), element_type = c("rect", "text", "text", "line", 
                                                                                          "text", "text", "text", "text"), fills = list(list(list(blendMode = "NORMAL", 
                                                                                                                                                  type = "SOLID", color = list(r = 0.372549027204514, g = 0.74117648601532, 
                                                                                                                                                                               b = 0.87058824300766, a = 1))), list(list(blendMode = "NORMAL", 
                                                                                                                                                                                                                         type = "SOLID", color = list(r = 0, g = 0, b = 0, a = 1))), 
                                                                                                                                        list(list(blendMode = "NORMAL", type = "SOLID", color = list(
                                                                                                                                          r = 0, g = 0, b = 0, a = 1))), list(list(blendMode = "NORMAL", 
                                                                                                                                                                                   type = "SOLID", color = list(r = 0.372549027204514, g = 0.74117648601532, 
                                                                                                                                                                                                                b = 0.87058824300766, a = 1))), list(list(blendMode = "NORMAL", 
                                                                                                                                                                                                                                                          type = "SOLID", color = list(r = 0.690196096897125, g = 0.690196096897125, 
                                                                                                                                                                                                                                                                                       b = 0.690196096897125, a = 1))), list(list(blendMode = "NORMAL", 
                                                                                                                                                                                                                                                                                                                                  type = "SOLID", color = list(r = 0, g = 0, b = 0, a = 1))), 
                                                                                                                                        list(list(blendMode = "NORMAL", type = "SOLID", color = list(
                                                                                                                                          r = 0, g = 0, b = 0, a = 1))), list(list(blendMode = "NORMAL", 
                                                                                                                                                                                   type = "SOLID", color = list(r = 0.992156863212585, g = 0.650980412960052, 
                                                                                                                                                                                                                b = 0.890196084976196, a = 1)))), strokes = list(
                                                                                                                                                                                                                  list(list(blendMode = "NORMAL", type = "SOLID", color = list(
                                                                                                                                                                                                                    r = 0.966666638851166, g = 0.0563889145851135, b = 0.0563889145851135, 
                                                                                                                                                                                                                    a = 1))), NULL, NULL, NULL, NULL, NULL, NULL, NULL), 
                                         strokeWeight = c(1, 1, 1, 1, 1, 1, 1, 1), opacity = c(NA, 
                                                                                               NA, NA, NA, 0.889999985694885, NA, NA, NA), style = list(
                                                                                                 NULL, list(fontFamily = "Roboto", fontPostScriptName = NULL, 
                                                                                                            fontWeight = 400L, textAutoResize = "HEIGHT", fontSize = 9, 
                                                                                                            textAlignHorizontal = "LEFT", textAlignVertical = "TOP", 
                                                                                                            letterSpacing = 0.36, lineHeightPx = 10.546875, lineHeightPercent = 100, 
                                                                                                            lineHeightUnit = "INTRINSIC_%"), list(fontFamily = "Roboto", 
                                                                                                                                                  fontPostScriptName = NULL, fontWeight = 400L, textAutoResize = "HEIGHT", 
                                                                                                                                                  fontSize = 11, textAlignHorizontal = "LEFT", textAlignVertical = "TOP", 
                                                                                                                                                  letterSpacing = 0.44, lineHeightPx = 12.890625, lineHeightPercent = 100, 
                                                                                                                                                  lineHeightUnit = "INTRINSIC_%"), NULL, list(fontFamily = "Roboto", 
                                                                                                                                                                                              fontPostScriptName = NULL, fontWeight = 400L, fontSize = 9, 
                                                                                                                                                                                              textAlignHorizontal = "LEFT", textAlignVertical = "TOP", 
                                                                                                                                                                                              letterSpacing = 0, lineHeightPx = 10.546875, lineHeightPercent = 100, 
                                                                                                                                                                                              lineHeightUnit = "INTRINSIC_%"), list(fontFamily = "Roboto", 
                                                                                                                                                                                                                                    fontPostScriptName = NULL, fontWeight = 400L, fontSize = 11, 
                                                                                                                                                                                                                                    textAlignHorizontal = "LEFT", textAlignVertical = "TOP", 
                                                                                                                                                                                                                                    letterSpacing = 0.44, lineHeightPx = 12.890625, lineHeightPercent = 100, 
                                                                                                                                                                                                                                    lineHeightUnit = "INTRINSIC_%"), list(fontFamily = "Roboto", 
                                                                                                                                                                                                                                                                          fontPostScriptName = "Roboto-Light", fontWeight = 300L, 
                                                                                                                                                                                                                                                                          textAutoResize = "HEIGHT", fontSize = 12, textAlignHorizontal = "LEFT", 
                                                                                                                                                                                                                                                                          textAlignVertical = "TOP", letterSpacing = 0.48, 
                                                                                                                                                                                                                                                                          lineHeightPx = 14.0625, lineHeightPercent = 100, 
                                                                                                                                                                                                                                                                          lineHeightUnit = "INTRINSIC_%"), list(fontFamily = "Roboto", 
                                                                                                                                                                                                                                                                                                                fontPostScriptName = "Roboto-Light", fontWeight = 300L, 
                                                                                                                                                                                                                                                                                                                textAutoResize = "WIDTH_AND_HEIGHT", fontSize = 20, 
                                                                                                                                                                                                                                                                                                                textAlignHorizontal = "LEFT", textAlignVertical = "TOP", 
                                                                                                                                                                                                                                                                                                                letterSpacing = 0.8, lineHeightPx = 23.4375, lineHeightPercent = 100, 
                                                                                                                                                                                                                                                                                                                lineHeightUnit = "INTRINSIC_%"))), row.names = c(NA, 
                                                                                                                                                                                                                                                                                                                                                                 -8L), class = c("tbl_df", "tbl", "data.frame")))
  # end of long dput ----
  
  
  
  data_with_error_type <- toy_raw_file_content %>% 
    raw_to_design_tibble() %>% 
    dplyr::mutate(type = dplyr::case_when(
      element_name == "panel_background" ~ "TEXT",
      TRUE ~ element_name
    ))
  
  expect_error(data_with_error_type %>% add_ggplot_type())
    
})
