# WARNING - Generated by {fusen} from /dev/flat_ggplot_theme.Rmd: do not edit by hand

test_that("create_theme_fun works", {

  data(toy_raw_file_content)

  my_theme <- toy_raw_file_content %>% 
    create_theme_fun()
  
  expect_true(inherits(my_theme, "function"))
  
})
