# WARNING - Generated by {fusen} from /dev/flat_figma_design_extraction.Rmd: do not edit by hand

#' Add the type of the ggplot2 elements (i.e. "rect", "line" or "text")
#'
#' @param .data Tibble. An object returned by \code{swatch::\link{raw_to_design_tibble}()}
#' 
#' @importFrom readr read_rds 
#' @importFrom dplyr left_join mutate case_when filter select everything
#' @importFrom cli cli_alert_danger
#'
#' @return The same tibble with an extra column with the ggplot2 type (i.e. "rect", "line" or "text").
#' @export
#' @examples
#' data(toy_raw_file_content)
#' data_design <- toy_raw_file_content %>% 
#'   raw_to_design_tibble()
#' data_design %>% 
#'   add_ggplot_type()
add_ggplot_type <- function(.data) {
  
  corresp_element_type <- read_rds(system.file("corresp_element_type.rds",
                                               package = "swatch"))
  joined_data <- .data %>% 
    left_join(corresp_element_type, 
              by = "element_name") %>% 
    mutate(check_type = case_when(
      type == "VECTOR" & (element_type %in% c("rect", "line")) ~ "ok",
      type == "TEXT" & element_type == "text" ~ "ok",
      TRUE ~ "not ok"
    ))
  
  unconsistent_type <- joined_data %>% 
    filter(check_type == "not ok")
  
  if (nrow(unconsistent_type) != 0) {
    stop(cli_alert_danger("Inconsistent type of the ggplot2 elements. Incoherence between the type returned by Figma and the type specified in ggplot2."))
  } 
  
  joined_data <- joined_data %>% 
    select(-type, -check_type) %>% 
    select(element_name, element_type, everything())
  
  return(joined_data)
  
}
