# WARNING - Generated by {fusen} from /dev/flat_ggplot_theme.Rmd: do not edit by hand

#' Determine if the required font families are present on the system
#' 
#' @param .data Tibble. {ggplot2} elements as created by \code{architekter::\link{extract_ggplot_theme}()}
#' 
#' @importFrom systemfonts system_fonts
#' @importFrom dplyr filter distinct pull left_join mutate case_when select
#' @importFrom cli cli_alert_danger
#' @importFrom glue glue glue_collapse
#' @importFrom showtext showtext_auto
#' 
#' @return A tibble with the correct font family. And a message if one of the fonts is missing.
#' 
#' @export
#' @examples
#' data(toy_raw_file_content)
#' 
#' toy_raw_file_content %>% 
#'   extract_ggplot_theme() %>% 
#'   check_font_families()
check_font_families <- function(.data){

  showtext_auto()
  
  #_ extract available fonts on the system
  available_fonts <- system_fonts() %>% 
    select(name, family, style) %>% 
    rename(ps_name = name) %>% 
    mutate(family = paste(family, style)) %>% 
    select(ps_name, family)
  
  print(available_fonts %>% filter(stringr::str_detect(family, "Roboto")))
  
  #_ replace the ps_name with the family
  .data <- .data %>% 
    left_join(available_fonts, 
              by = c("font_ps_name" = "ps_name")) %>% 
    mutate(family = case_when(
      !is.na(font_ps_name) ~ family,
      !is.na(font_family) ~ font_family, 
      TRUE ~ family
      )
    )
  
  #_ check if needed fonts have been found
  .data <- .data %>% 
    mutate(
      check_font = case_when(
        is.na(font_family) & is.na(font_ps_name) ~ NA_character_,
        !is.na(font_family) & !is.na(family) ~ "found",
        !is.na(font_ps_name) & !is.na(family) ~ "found",
        TRUE ~ "not found"
        )) %>% 
    mutate(
      font_to_install = case_when(
        check_font == "not found" & !is.na(font_ps_name) ~ font_ps_name,
        check_font == "not found" & !is.na(font_family) ~ font_family,
        TRUE ~ NA_character_
      )
    ) %>% 
    select(-font_family, -font_ps_name)

  print(.data %>% select(family, check_font, font_to_install))
  
  #_ stop if there is a font that is not installed
  if(any(.data %>% pull(check_font) == "not found", na.rm = TRUE)) {
    message(cli_alert_danger(glue("The following fonts are required and not installed on the system: {glue_collapse(.data %>% distinct(font_to_install) %>% pull(font_to_install), sep = ', ')}\nPlease install these fonts on your system before to try again\nYou can see ?sysfonts::font_add() and ?sysfonts::font_add_google()")))
  }
  
  #_ delete unnecessary cols
  .data <- .data %>% 
    select(-check_font, -font_to_install)
    
  return(.data)
  
}
