# WARNING - Generated by {fusen} from /dev/flat_figma_design_extraction.Rmd: do not edit by hand

# #' Extract the {ggplot2} design content of a file.
# #'
# #' @param ggplot_element Character. Name of the {ggplot2} element, as defined in \link[ggplot2]{theme}.
# #' @param file_content List. Content of the Figma file, as returned by \link[swatch]{get_file_content}.
# #'
# #' @importFrom purrr map_chr
# #' @importFrom grDevices rgb
# #' @importFrom grDevices rgb
# #' 
# #' @return List. The {ggplot2} element properties.
# #' @export
#' @examples
#' # file_content <- get_file_content(file_key = "wRqIvMmymzSPuj0sEhnORb",
#' #                                  acess_token = Sys.getenv("FIGMA_TOKEN"))
#' # 
#' # get_ggplot_element_design(ggplot_element = "panel_background",
#' #                           file_content = file_content)
#' # 
#' # get_ggplot_element_design(ggplot_element = "panel_grid",
#' #                           file_content = file_content)
# get_ggplot_element_design <- function(ggplot_element, file_content) {
#   
#   # Find info about elements ids and names in Figma
#   main_components_names <- file_content$components %>% 
#     map_chr(~ .x$name)
#   
#   sub_components_id <- file_content$document$children[[1]]$children %>% 
#     map_chr(~ .x$id)
#   
#   # Find the id of the ggplot2 element
#   element_id <- names(main_components_names[main_components_names == ggplot_element])
# 
#   # Extract the desing content of the ggplot2 element
#   element_design <- file_content$document$children[[1]]$children[[which(sub_components_id == element_id)]]
# 
#   # Construct a list with the desing elements
#   list_element_design <- list()
# 
#   if (ggplot_element == "panel_background") {
#     
#     # Fill color
#     list_element_design[[length(list_element_design) + 1]] <- rgb(element_design$backgroundColor$r, 
#                                                                   element_design$backgroundColor$g,
#                                                                   element_design$backgroundColor$b,
#                                                                   maxColorValue = 1)
#     names(list_element_design)[[length(list_element_design)]] <- "fill_color"
#     
#     # Fill opacity
#     list_element_design[[length(list_element_design) + 1]] <- element_design$backgroundColor$a
#     names(list_element_design)[[length(list_element_design)]] <- "fill_opacity"
#     
#   }
#   
#   if (ggplot_element %in% c("panel_background", "panel_grid")) {
#     
#     # Stroke color
#     list_element_design[[length(list_element_design) + 1]] <- rgb(element_design$strokes[[1]]$color$r, 
#                                                                   element_design$strokes[[1]]$color$g,
#                                                                   element_design$strokes[[1]]$color$b,
#                                                                   maxColorValue = 1)
#     names(list_element_design)[[length(list_element_design)]] <- "stroke_color"
#     
#     # Stroke opacity
#     list_element_design[[length(list_element_design) + 1]] <- element_design$strokes[[1]]$color$a
#     names(list_element_design)[[length(list_element_design)]] <- "stroke_opacity"
#     
#     # Stroke weight
#     list_element_design[[length(list_element_design) + 1]] <- element_design$strokeWeigh
#     names(list_element_design)[[length(list_element_design)]] <- "stroke_weight"
#     
#   }
#   
#   return(list_element_design)
#   
# }
